### ISSUE TITLE
error when logging in to admin console on windows 

### ISSUE THREAD

**Issue by mohammadswaidan** [openequella/openEQUELLA-admin-console-package#146]
We downloaded the latest admin console version v1.3.1 , we set the correct server trying to log in with `TLE_ADMINISTRATOR` user , the login failed with error in the cmd:

```
Exception in thread "main" java.lang.RuntimeException: org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [https://lor.medadstg.com/medad/invoker/com.tle.core.remoting.RemotePluginDownloadService.service]; nested exception is java.io.IOException: Did not receive successful HTTP response: status code = 401, status message = [null]
        at com.tle.admin.boot.Bootstrap.run(Bootstrap.java:129)
        at com.tle.admin.boot.Bootstrap.main(Bootstrap.java:71)
Caused by: org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [https://lor.medadstg.com/medad/invoker/com.tle.core.remoting.RemotePluginDownloadService.service]; nested exception is java.io.IOException: Did not receive successful HTTP response: status code = 401, status message = [null]
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:234)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:160)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:241)
        at jdk.proxy1/jdk.proxy1.$Proxy0.getAllPluginDetails(Unknown Source)
        at com.tle.admin.PluginServiceImpl.registerPlugins(PluginServiceImpl.java:90)
        at com.tle.admin.boot.Bootstrap.run(Bootstrap.java:118)
        ... 1 more
Caused by: java.io.IOException: Did not receive successful HTTP response: status code = 401, status message = [null]
        at org.springframework.remoting.httpinvoker.SimpleHttpInvokerRequestExecutor.validateResponse(SimpleHttpInvokerRequestExecutor.java:189)
        at org.springframework.remoting.httpinvoker.SimpleHttpInvokerRequestExecutor.doExecuteRequest(SimpleHttpInvokerRequestExecutor.java:93)
        at org.springframework.remoting.httpinvoker.AbstractHttpInvokerRequestExecutor.executeRequest(AbstractHttpInvokerRequestExecutor.java:141)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:209)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:191)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:157)
        ... 6 more
```

**Comment by edalex-ian** [comment]
Hi @mohammadswaidan ,

In part of that error I see:

```
Caused by: java.io.IOException: Did not receive successful HTTP response: status code = 401, status message = [null]
```

With `401` indicating to me an authentication issue. Assuming you have correctly typed `TLE_ADMINISTRATOR` it would seem possibly your password is incorrect. Have you confirmed you're using the correct password by logging into https://lor.medadstg.com/medad/ with `TLE_ADMINISTRATOR` and that password?

**Comment by mohammadswaidan** [comment]
Hello , thank you for your time 
infact yes I am pretty sure the password is correct as I use it to login to site as admin and to my institution as well

**Comment by islam56naser** [comment]
@edalex-ian @mohammadswaidan I'm having the same issue, is there any update on this ?

**Comment by edalex-ian** [comment]
Hi again,

Maybe a couple of general questions for you both:

- What version of oEQ are you running?
- What operating system is your oEQ instance running on?
- Are there any firewalls in front of your instances?

Lastly, @mohammadswaidan I note you said:

> password is correct as I use it to login to site as admin

When you say 'as admin' do you mean as `TLE_ADMINISTRATOR` via the login page? Or, as you saying the password you use when you click on the 'Administer server' link?

**Comment by mohammadswaidan** [comment]
Hi,
First, the oEQ version deployed was 2023.2.0 , we tried the latest admin console v1.3.1 , and also tried v1.21 
We updated the oEQ to the latest version 2024.1.0 , and tried the admin console v1.3.1 
same error in all cases
Of course I am using the TLE_ADMINISTRATOR  with password that we used to login to the institution

**Comment by edalex-ian** [comment]
Thanks for the version information @mohammadswaidan , you missed my query on OS and firewalls. That info could help.

Also, regarding:

> Of course I am using the TLE_ADMINISTRATOR with password that we used to login to the institution

Just as per my last comment this password can be (and often is) different to the one used on the other link I mention above.

But if you're sure with all the above, feel free to reach out for support via support@edalex.com.

**Comment by edalex-ian** [comment]
Almost  year since last activity, closing.

If further help is needed, please let us know.
